// Generated by Selenium IDE
// Adding Contacts and Verifying the success
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ContactAllTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contactAll() {
    driver.get("https://dev.keela.co/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.cssSelector(".nav-main > .nav-main-item:nth-child(3) .nav-main-link-name")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.id("YdLp8fQbrBjzXu9LE")).sendKeys("Sita");
    driver.findElement(By.id("4f8ZudnEmhtiZuA48")).click();
    driver.findElement(By.id("4f8ZudnEmhtiZuA48")).sendKeys("Kumari");
    driver.findElement(By.id("8xLcSMLnRkXhdF9k9")).click();
    driver.findElement(By.id("8xLcSMLnRkXhdF9k9")).sendKeys("Shrestha");
    driver.findElement(By.id("CCaXoYjPsuJ84xwqB")).click();
    driver.findElement(By.id("CCaXoYjPsuJ84xwqB")).sendKeys("Sita@gmail.com");
    driver.findElement(By.id("88k65uFqtwADtvJmo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("88k65uFqtwADtvJmo"));
      dropdown.findElement(By.xpath("//option[. = 'Opted In']")).click();
    }
    driver.findElement(By.id("9He5jtaTkAXCMskeA")).click();
    driver.findElement(By.id("9He5jtaTkAXCMskeA")).sendKeys("9898989898");
    driver.findElement(By.id("pf7qikkwLa8uMF5n9")).click();
    driver.findElement(By.linkText("AA Transport Company")).click();
    driver.findElement(By.id("2td6pRHtJXByAQJow")).click();
    driver.findElement(By.id("2td6pRHtJXByAQJow")).sendKeys("QA");
    driver.findElement(By.cssSelector(".col-lg-6:nth-child(3) > div:nth-child(3) .form-group")).click();
    driver.findElement(By.id("RpKqkLqyzZrHchF4i")).click();
    driver.findElement(By.linkText("Transport")).click();
    driver.findElement(By.id("7TzsZZngrLPsh9HhF")).click();
    driver.findElement(By.id("7TzsZZngrLPsh9HhF")).sendKeys("Transport");
    driver.findElement(By.id("G9FqeFzsSKP5bYgeN")).click();
    {
      WebElement dropdown = driver.findElement(By.id("G9FqeFzsSKP5bYgeN"));
      dropdown.findElement(By.xpath("//option[. = 'High']")).click();
    }
    driver.findElement(By.cssSelector(".vs__selected-options > .form-control:nth-child(1)")).click();
    driver.findElement(By.linkText("name")).click();
    driver.findElement(By.cssSelector(".vs__selected-options > .form-control:nth-child(1)")).click();
    driver.findElement(By.linkText("Donation")).click();
    driver.findElement(By.id("pFxJhBeGKFrGCLdeHday")).click();
    {
      WebElement dropdown = driver.findElement(By.id("pFxJhBeGKFrGCLdeHday"));
      dropdown.findElement(By.xpath("//option[. = '16']")).click();
    }
    driver.findElement(By.id("pFxJhBeGKFrGCLdeHmonth")).click();
    {
      WebElement dropdown = driver.findElement(By.id("pFxJhBeGKFrGCLdeHmonth"));
      dropdown.findElement(By.xpath("//option[. = 'May']")).click();
    }
    driver.findElement(By.id("pFxJhBeGKFrGCLdeHyear")).click();
    {
      WebElement dropdown = driver.findElement(By.id("pFxJhBeGKFrGCLdeHyear"));
      dropdown.findElement(By.xpath("//option[. = '1995']")).click();
    }
    driver.findElement(By.id("Bp7JMX7F3JGrWXDNwstreet")).click();
    driver.findElement(By.id("Bp7JMX7F3JGrWXDNwstreet")).sendKeys("Pulchowk");
    driver.findElement(By.id("Bp7JMX7F3JGrWXDNwstreet")).click();
    driver.findElement(By.id("Bp7JMX7F3JGrWXDNwstreet")).sendKeys("Pulchowk");
    driver.findElement(By.cssSelector(".col-lg-6:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".v--modal-background-click")).click();
    driver.findElement(By.cssSelector(".v--modal-background-click")).click();
    driver.findElement(By.cssSelector("div:nth-child(9) .form-group")).click();
    driver.findElement(By.id("Bp7JMX7F3JGrWXDNwregion")).sendKeys("Bagmati");
    driver.findElement(By.cssSelector(".v--modal-background-click")).click();
    driver.findElement(By.cssSelector(".btn-primary:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("span > span > span:nth-child(2)")).getText(), is("- Profile"));
  }
}
