// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void create() {
    driver.get("https://dev.keela.co/");
    driver.manage().window().setSize(new Dimension(945, 1012));
    driver.findElement(By.cssSelector(".nav-main > .nav-main-item:nth-child(3) .nav-main-link-name")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.id("vneEjaW23mbaLKvbk")).click();
    driver.findElement(By.id("vneEjaW23mbaLKvbk")).sendKeys(vars.get("firstname").toString());
    driver.findElement(By.id("6MTCKKfQbtYA7Ja8G")).click();
    driver.findElement(By.id("6MTCKKfQbtYA7Ja8G")).sendKeys(vars.get("middlename").toString());
    driver.findElement(By.id("DoBtz4LMiingqeePa")).click();
    driver.findElement(By.id("DoBtz4LMiingqeePa")).sendKeys(vars.get("lastname").toString());
    driver.findElement(By.cssSelector(".btn-primary:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".block:nth-child(2) .block-title")).getText(), is("Personal Info"));
  }
}
